Fix SC2028 warning
This occurs on macos-12 run but despite having the same macos locally, I don't receive that warning when running shellcheck. We don't need the text formatting so easier to just remove that. Also added a test for failure case since that's easy to test for.

diff --git a/dotfiles/bin/start-development b/dotfiles/bin/start-development
--- a/dotfiles/bin/start-development
+++ b/dotfiles/bin/start-development
@@ -14,6 +14,6 @@ elif [ -f ./Procfile ]; then
 elif [ -f ./package.json ]; then
   ( set -x; npm run start )
 else
-  echo "\033[1;31m** No dev server **\033[0m"
-  echo "Looking for a Procfile(.dev) or package.json file."
+  echo "Error: No dev server found. Looking for a Procfile.dev, Procfile or package.json file."
+  exit 1
 fi
